Feature/encrypt
yop-platform/yop-java-sdk pull request #33
Opened 2022-04-14 02:22 UTC by yop-wdc

2022-04-14 14:03 UTC, yop-developer commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/YopConstants.java
> +    String YOP_WORK_KEY_ENCRYPT_ALG_SM4 = SM4_CBC_PKCS7PADDING;
PKCS5Padding，固定8字节

2022-04-14 14:06 UTC, yop-developer commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/auth/credentials/provider/YopPlatformCredentialsProvider.java
> +        // 方案调整 先不实现了
这里是干嘛的？

2022-04-14 14:10 UTC, yop-developer commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/model/YopRequestConfig.java
> +    private String encryptAlg = SM4_CBC_PKCS7PADDING;
PKCS5Padding，固定8字节

2022-04-14 14:35 UTC, yop-developer requested changes
PKCS5Padding

2022-04-15 06:18 UTC, yop-wdc commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/model/YopRequestConfig.java
> +    private String encryptAlg = SM4_CBC_PKCS7PADDING;
OK

2022-06-29 03:01 UTC, closed without merging