Feature/sentinel
yop-platform/yop-java-sdk pull request #55
Opened 2023-05-04 03:23 UTC by yop-wdc

2023-05-04 06:27 UTC, Teacher-Tony commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/base/cache/YopDegradeRuleWrapper.java
> +        final double errRatio = ((double) hystrixConfig.getCircuitBreakerErrorThresholdPercentage()) / 100.00;
咋不直接填写小数，还非得进来再除以100

2023-05-04 06:31 UTC, Teacher-Tony commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/base/cache/YopDegradeRuleWrapper.java
> +    public synchronized static void initDegradeRule(List<URI> serverRoots, YopHystrixConfig hystrixConfig) {
为什么不写双重校验锁

2023-05-04 06:43 UTC, Teacher-Tony requested changes

2023-05-04 06:43 UTC, Teacher-Tony commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/base/cache/YopDegradeRuleWrapper.java
> +            String resource = StringUtils.substringBefore(serverRoot.toString(), "?");
这是啥意思？

2023-05-04 06:43 UTC, Teacher-Tony commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/base/cache/YopDegradeRuleWrapper.java
> +                .setMinRequestAmount(hystrixConfig.getCircuitBreakerRequestVolumeThreshold())
笔数的情况也需要这个值？

2023-05-04 06:43 UTC, Teacher-Tony commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/base/cache/YopDegradeRuleWrapper.java
> +    public static void addDegradeRule(URI serverRoot, YopHystrixConfig hystrixConfig) {
干啥的方法

2023-05-04 06:43 UTC, Teacher-Tony commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/client/ClientHandlerImpl.java
> +        final YopHystrixConfig hystrixConfig = this.clientConfiguration.getHystrixConfig();
要不要改个名

2023-05-04 06:43 UTC, Teacher-Tony commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/client/ClientHandlerImpl.java
> +    private class YopHystrixCircuitBreaker implements YopCircuitBreaker {
Hystrix是不是不用保留了

2023-05-04 08:42 UTC, yop-wdc commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/base/cache/YopDegradeRuleWrapper.java
> +    public static void addDegradeRule(URI serverRoot, YopHystrixConfig hystrixConfig) {
手动指定域名时，添加熔断规则

2023-05-04 08:46 UTC, Teacher-Tony commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/base/cache/YopDegradeRuleHelper.java
> +    public static void addDegradeRule(URI serverRoot, YopCircuitBreakerConfig circuitBreakerConfig) {
和initDegradeRuleForResource高度类似

2023-05-04 08:49 UTC, Teacher-Tony commented on yop-java-sdk-base/src/main/resources/config/yop_sdk_config_default.json
> +      "min_request_count_threshold": 10,
一秒钟10笔，很多商户都达不到吧

2023-06-02 02:06 UTC, Teacher-Tony commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/base/cache/YopDegradeRuleHelper.java
> +            return;
这么写不会出问题嘛

2023-06-02 02:07 UTC, Teacher-Tony commented on yop-java-sdk-base/src/main/java/com/yeepay/yop/sdk/base/cache/YopDegradeRuleHelper.java
> +                degradeRule.setMinRequestAmount(Double.valueOf(configRule.getCount()).intValue());
为什么不直接使用doubleValue()

2023-06-02 04:02 UTC, Teacher-Tony approved these changes

2023-06-02 04:04 UTC, merged